/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class AdminTeamsSettingsSetIconSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AdminTeamsSettingsSetIconRequestBody extends SpeakeasyBase {
  /**
   * Image URL for the icon
   */
  @SpeakeasyMetadata({ data: "form, name=image_url" })
  imageUrl: string;

  /**
   * ID for the workspace to set the icon for.
   */
  @SpeakeasyMetadata({ data: "form, name=team_id" })
  teamId: string;

  /**
   * Authentication token. Requires scope: `admin.teams:write`
   */
  @SpeakeasyMetadata({ data: "form, name=token" })
  token: string;
}

export class AdminTeamsSettingsSetIconResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  defaultErrorTemplate?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  defaultSuccessTemplate?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
