/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class AdminUsersSetAdminSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AdminUsersSetAdminApplicationJSON extends SpeakeasyBase {
  /**
   * The ID (`T1234`) of the workspace.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "team_id" })
  teamId: string;

  /**
   * The ID of the user to designate as an admin.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "user_id" })
  userId: string;
}

export class AdminUsersSetAdminRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: AdminUsersSetAdminApplicationJSON;

  /**
   * Authentication token. Requires scope: `admin.users:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class AdminUsersSetAdminResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  defaultErrorTemplate?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  defaultSuccessTemplate?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
