/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class AdminUsergroupsListChannelsSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AdminUsergroupsListChannelsRequest extends SpeakeasyBase {
  /**
   * Flag to include or exclude the count of members per channel.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=include_num_members",
  })
  includeNumMembers?: boolean;

  /**
   * ID of the the workspace.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=team_id",
  })
  teamId?: string;

  /**
   * Authentication token. Requires scope: `admin.usergroups:read`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;

  /**
   * ID of the IDP group to list default channels for.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=usergroup_id",
  })
  usergroupId: string;
}

export class AdminUsergroupsListChannelsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Typical error response if the token provided is not associated with an Org Admin or Owner
   */
  @SpeakeasyMetadata()
  defaultErrorTemplate?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  defaultSuccessTemplate?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
