/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class AdminUsersAssignSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AdminUsersAssignApplicationJSON extends SpeakeasyBase {
  /**
   * Comma separated values of channel IDs to add user in the new workspace.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channel_ids" })
  channelIds?: string;

  /**
   * True if user should be added to the workspace as a guest.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "is_restricted" })
  isRestricted?: boolean;

  /**
   * True if user should be added to the workspace as a single-channel guest.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "is_ultra_restricted" })
  isUltraRestricted?: boolean;

  /**
   * The ID (`T1234`) of the workspace.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "team_id" })
  teamId: string;

  /**
   * The ID of the user to add to the workspace.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "user_id" })
  userId: string;
}

export class AdminUsersAssignRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: AdminUsersAssignApplicationJSON;

  /**
   * Authentication token. Requires scope: `admin.users:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class AdminUsersAssignResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  defaultErrorTemplate?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  defaultSuccessTemplate?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
