/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class AdminConversationsConvertToPrivateSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AdminConversationsConvertToPrivateApplicationJSON extends SpeakeasyBase {
  /**
   * The channel to convert to private.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channel_id" })
  channelId: string;
}

export class AdminConversationsConvertToPrivateRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: AdminConversationsConvertToPrivateApplicationJSON;

  /**
   * Authentication token. Requires scope: `admin.conversations:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class AdminConversationsConvertToPrivateResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  adminConversationsConvertToPrivateErrorSchema?: Record<
    string,
    Record<string, any>
  >;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  adminConversationsConvertToPrivateSchema?: Record<
    string,
    Record<string, any>
  >;
}
