/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class AdminAppsApproveSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AdminAppsApproveApplicationJSON extends SpeakeasyBase {
  /**
   * The id of the app to approve.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "app_id" })
  appId?: string;

  /**
   * The id of the request to approve.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "request_id" })
  requestId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "team_id" })
  teamId?: string;
}

export class AdminAppsApproveRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody?: AdminAppsApproveApplicationJSON;

  /**
   * Authentication token. Requires scope: `admin.apps:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class AdminAppsApproveResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  defaultErrorTemplate?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  defaultSuccessTemplate?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
