/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class AdminConversationsRenameSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AdminConversationsRenameApplicationJSON extends SpeakeasyBase {
  /**
   * The channel to rename.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channel_id" })
  channelId: string;

  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;
}

export class AdminConversationsRenameRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: AdminConversationsRenameApplicationJSON;

  /**
   * Authentication token. Requires scope: `admin.conversations:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class AdminConversationsRenameResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  adminConversationsRenameSchema?: Record<string, Record<string, any>>;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  adminConversationsUnarchiveErrorSchema?: Record<string, Record<string, any>>;
}
