/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class AdminTeamsSettingsSetDiscoverabilitySecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AdminTeamsSettingsSetDiscoverabilityApplicationJSON extends SpeakeasyBase {
  /**
   * This workspace's discovery setting. It must be set to one of `open`, `invite_only`, `closed`, or `unlisted`.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "discoverability" })
  discoverability: string;

  /**
   * The ID of the workspace to set discoverability on.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "team_id" })
  teamId: string;
}

export class AdminTeamsSettingsSetDiscoverabilityRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: AdminTeamsSettingsSetDiscoverabilityApplicationJSON;

  /**
   * Authentication token. Requires scope: `admin.teams:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class AdminTeamsSettingsSetDiscoverabilityResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  defaultErrorTemplate?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  defaultSuccessTemplate?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
