/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class AdminConversationsSetConversationPrefsSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AdminConversationsSetConversationPrefsApplicationJSON extends SpeakeasyBase {
  /**
   * The channel to set the prefs for
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channel_id" })
  channelId: string;

  /**
   * The prefs for this channel in a stringified JSON format.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "prefs" })
  prefs: string;
}

export class AdminConversationsSetConversationPrefsRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: AdminConversationsSetConversationPrefsApplicationJSON;

  /**
   * Authentication token. Requires scope: `admin.conversations:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class AdminConversationsSetConversationPrefsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  adminConversationsSetConversationPrefsErrorSchema?: Record<
    string,
    Record<string, any>
  >;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  adminConversationsSetConversationPrefsSchema?: Record<
    string,
    Record<string, any>
  >;
}
