/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class AdminTeamsCreateSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AdminTeamsCreateApplicationJSON extends SpeakeasyBase {
  /**
   * Description for the team.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "team_description" })
  teamDescription?: string;

  /**
   * Who can join the team. A team's discoverability can be `open`, `closed`, `invite_only`, or `unlisted`.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "team_discoverability" })
  teamDiscoverability?: string;

  /**
   * Team domain (for example, slacksoftballteam).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "team_domain" })
  teamDomain: string;

  /**
   * Team name (for example, Slack Softball Team).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "team_name" })
  teamName: string;
}

export class AdminTeamsCreateRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: AdminTeamsCreateApplicationJSON;

  /**
   * Authentication token. Requires scope: `admin.teams:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class AdminTeamsCreateResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  defaultErrorTemplate?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  defaultSuccessTemplate?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
