/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class AppsPermissionsInfoSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AppsPermissionsInfoRequest extends SpeakeasyBase {
  /**
   * Authentication token. Requires scope: `none`
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=token" })
  token?: string;
}

export class AppsPermissionsInfoResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Standard failure response when used with an invalid token
   */
  @SpeakeasyMetadata()
  appsPermissionsInfoErrorSchema?: Record<string, Record<string, any>>;

  /**
   * Standard success response when used with a user token
   */
  @SpeakeasyMetadata()
  appsPermissionsInfoSchema?: Record<string, Record<string, any>>;
}
