/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class AppsPermissionsRequestSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AppsPermissionsRequestRequest extends SpeakeasyBase {
  /**
   * A comma separated list of scopes to request for
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=scopes",
  })
  scopes: string;

  /**
   * Authentication token. Requires scope: `none`
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=token" })
  token: string;

  /**
   * Token used to trigger the permissions API
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=trigger_id",
  })
  triggerId: string;
}

export class AppsPermissionsRequestResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Standard failure response when trigger_id is invalid
   */
  @SpeakeasyMetadata()
  appsPermissionsRequestErrorSchema?: Record<string, Record<string, any>>;

  /**
   * Standard success response when used with a user token
   */
  @SpeakeasyMetadata()
  appsPermissionsRequestSchema?: Record<string, Record<string, any>>;
}
