/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class AuthTestSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class AuthTestRequest extends SpeakeasyBase {
  /**
   * Authentication token. Requires scope: `none`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class AuthTestResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Standard failure response when used with an invalid token
   */
  @SpeakeasyMetadata()
  authTestErrorSchema?: Record<string, Record<string, any>>;

  /**
   * Standard success response when used with a user token
   */
  @SpeakeasyMetadata()
  authTestSuccessSchema?: Record<string, Record<string, any>>;
}
