/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class ChatGetPermalinkSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class ChatGetPermalinkRequest extends SpeakeasyBase {
  /**
   * The ID of the conversation or channel containing the message
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=channel",
  })
  channel: string;

  /**
   * A message's `ts` value, uniquely identifying it within a channel
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=message_ts",
  })
  messageTs: string;

  /**
   * Authentication token. Requires scope: `none`
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=token" })
  token: string;
}

export class ChatGetPermalinkResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Error response when channel cannot be found
   */
  @SpeakeasyMetadata()
  chatGetPermalinkErrorSchema?: Record<string, Record<string, any>>;

  /**
   * Standard success response
   */
  @SpeakeasyMetadata()
  chatGetPermalinkSuccessSchema?: Record<string, Record<string, any>>;
}
