/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class ConversationsCreateSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class ConversationsCreateApplicationJSON extends SpeakeasyBase {
  /**
   * Create a private channel instead of a public one
   */
  @SpeakeasyMetadata()
  @Expose({ name: "is_private" })
  isPrivate?: boolean;

  /**
   * Name of the public or private channel to create
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

export class ConversationsCreateRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody?: ConversationsCreateApplicationJSON;

  /**
   * Authentication token. Requires scope: `conversations:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token?: string;
}

export class ConversationsCreateResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Typical error response when name already in use
   */
  @SpeakeasyMetadata()
  conversationsCreateErrorSchema?: Record<string, Record<string, any>>;

  /**
   * If successful, the command returns a rather stark [conversation object](/types/conversation)
   */
  @SpeakeasyMetadata()
  conversationsCreateSuccessSchema?: Record<string, Record<string, any>>;
}
