/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class ConversationsRepliesSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class ConversationsRepliesRequest extends SpeakeasyBase {
  /**
   * Conversation ID to fetch thread from.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=channel",
  })
  channel?: string;

  /**
   * Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attribute returned by a previous request's `response_metadata`. Default value fetches the first "page" of the collection. See [pagination](/docs/pagination) for more detail.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=cursor",
  })
  cursor?: string;

  /**
   * Include messages with latest or oldest timestamp in results only when either timestamp is specified.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=inclusive",
  })
  inclusive?: boolean;

  /**
   * End of time range of messages to include in results.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=latest",
  })
  latest?: number;

  /**
   * The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the users list hasn't been reached.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=limit" })
  limit?: number;

  /**
   * Start of time range of messages to include in results.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=oldest",
  })
  oldest?: number;

  /**
   * Authentication token. Requires scope: `conversations:history`
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=token" })
  token?: string;

  /**
   * Unique identifier of a thread's parent message. `ts` must be the timestamp of an existing message with 0 or more replies. If there are no replies then just the single message referenced by `ts` will return - it is just an ordinary, unthreaded message.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=ts" })
  ts?: number;
}

export class ConversationsRepliesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  conversationsRepliesErrorSchema?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  conversationsRepliesSuccessSchema?: Record<string, Record<string, any>>;
}
