/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class DialogOpenSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class DialogOpenRequest extends SpeakeasyBase {
  /**
   * The dialog definition. This must be a JSON-encoded string.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=dialog",
  })
  dialog: string;

  /**
   * Authentication token. Requires scope: `none`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;

  /**
   * Exchange a trigger to post to the user.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=trigger_id",
  })
  triggerId: string;
}

export class DialogOpenResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Typical error response, before getting to any possible validation errors.
   */
  @SpeakeasyMetadata()
  dialogOpenErrorSchema?: Record<string, Record<string, any>>;

  /**
   * Typical success response is quite minimal.
   */
  @SpeakeasyMetadata()
  dialogOpenSchema?: Record<string, Record<string, any>>;
}
