/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class FilesRemoteAddSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class FilesRemoteAddRequestBody extends SpeakeasyBase {
  /**
   * Creator defined GUID for the file.
   */
  @SpeakeasyMetadata({ data: "form, name=external_id" })
  externalId?: string;

  /**
   * URL of the remote file.
   */
  @SpeakeasyMetadata({ data: "form, name=external_url" })
  externalUrl?: string;

  /**
   * type of file
   */
  @SpeakeasyMetadata({ data: "form, name=filetype" })
  filetype?: string;

  /**
   * A text file (txt, pdf, doc, etc.) containing textual search terms that are used to improve discovery of the remote file.
   */
  @SpeakeasyMetadata({ data: "form, name=indexable_file_contents" })
  indexableFileContents?: string;

  /**
   * Preview of the document via `multipart/form-data`.
   */
  @SpeakeasyMetadata({ data: "form, name=preview_image" })
  previewImage?: string;

  /**
   * Title of the file being shared.
   */
  @SpeakeasyMetadata({ data: "form, name=title" })
  title?: string;

  /**
   * Authentication token. Requires scope: `remote_files:write`
   */
  @SpeakeasyMetadata({ data: "form, name=token" })
  token?: string;
}

export class FilesRemoteAddResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  defaultErrorTemplate?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  defaultSuccessTemplate?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
