/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class UsergroupsEnableSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class UsergroupsEnableApplicationJSON extends SpeakeasyBase {
  /**
   * Include the number of users in the User Group.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "include_count" })
  includeCount?: boolean;

  /**
   * The encoded ID of the User Group to enable.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "usergroup" })
  usergroup: string;
}

export class UsergroupsEnableRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: UsergroupsEnableApplicationJSON;

  /**
   * Authentication token. Requires scope: `usergroups:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class UsergroupsEnableResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  usergroupsEnableErrorSchema?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  usergroupsEnableSchema?: Record<string, Record<string, any>>;
}
