/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class UsergroupsCreateSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class UsergroupsCreateApplicationJSON extends SpeakeasyBase {
  /**
   * A comma separated string of encoded channel IDs for which the User Group uses as a default.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channels" })
  channels?: string;

  /**
   * A short description of the User Group.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * A mention handle. Must be unique among channels, users and User Groups.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "handle" })
  handle?: string;

  /**
   * Include the number of users in each User Group.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "include_count" })
  includeCount?: boolean;

  /**
   * A name for the User Group. Must be unique among User Groups.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;
}

export class UsergroupsCreateRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: UsergroupsCreateApplicationJSON;

  /**
   * Authentication token. Requires scope: `usergroups:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class UsergroupsCreateResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  usergroupsCreateErrorSchema?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  usergroupsCreateSchema?: Record<string, Record<string, any>>;
}
