/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class UsersGetPresenceSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class UsersGetPresenceRequest extends SpeakeasyBase {
  /**
   * Authentication token. Requires scope: `users:read`
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=token" })
  token: string;

  /**
   * User to get presence info on. Defaults to the authed user.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=user" })
  user?: string;
}

export class UsersGetPresenceResponse extends SpeakeasyBase {
  /**
   * When requesting information for a different user, this method just returns the current presence (either `active` or `away`).
   */
  @SpeakeasyMetadata()
  apiMethodUsersGetPresence?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  usersCountsErrorSchema?: Record<string, Record<string, any>>;
}
