/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class UsergroupsUsersUpdateSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class UsergroupsUsersUpdateApplicationJSON extends SpeakeasyBase {
  /**
   * Include the number of users in the User Group.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "include_count" })
  includeCount?: boolean;

  /**
   * The encoded ID of the User Group to update.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "usergroup" })
  usergroup: string;

  /**
   * A comma separated string of encoded user IDs that represent the entire list of users for the User Group.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "users" })
  users: string;
}

export class UsergroupsUsersUpdateRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: UsergroupsUsersUpdateApplicationJSON;

  /**
   * Authentication token. Requires scope: `usergroups:write`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;
}

export class UsergroupsUsersUpdateResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  usergroupsUsersUpdateErrorSchema?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  usergroupsUsersUpdateSchema?: Record<string, Record<string, any>>;
}
