/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class UsergroupsUsersListSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class UsergroupsUsersListRequest extends SpeakeasyBase {
  /**
   * Allow results that involve disabled User Groups.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=include_disabled",
  })
  includeDisabled?: boolean;

  /**
   * Authentication token. Requires scope: `usergroups:read`
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=token" })
  token: string;

  /**
   * The encoded ID of the User Group to update.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=usergroup",
  })
  usergroup: string;
}

export class UsergroupsUsersListResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Standard failure response when used with an invalid token
   */
  @SpeakeasyMetadata()
  usergroupsUsersListErrorSchema?: Record<string, Record<string, any>>;

  /**
   * Standard success response when used with a user token
   */
  @SpeakeasyMetadata()
  usergroupsUsersListSchema?: Record<string, Record<string, any>>;
}
