/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class WorkflowsStepCompletedSecurity extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  slackAuth: string;
}

export class WorkflowsStepCompletedRequest extends SpeakeasyBase {
  /**
   * Key-value object of outputs from your step. Keys of this object reflect the configured `key` properties of your [`outputs`](/reference/workflows/workflow_step#output) array from your `workflow_step` object.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=outputs",
  })
  outputs?: string;

  /**
   * Authentication token. Requires scope: `workflow.steps:execute`
   */
  @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=token" })
  token: string;

  /**
   * Context identifier that maps to the correct workflow step execution.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=workflow_step_execute_id",
  })
  workflowStepExecuteId: string;
}

export class WorkflowsStepCompletedResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Typical error response
   */
  @SpeakeasyMetadata()
  defaultErrorTemplate?: Record<string, Record<string, any>>;

  /**
   * Typical success response
   */
  @SpeakeasyMetadata()
  defaultSuccessTemplate?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
