/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as utils from "../internal/utils";
import * as operations from "./models/operations";
import { AxiosInstance, AxiosRequestConfig, AxiosResponse } from "axios";

export class AdminConversationsRestrictAccess {
  _defaultClient: AxiosInstance;
  _securityClient: AxiosInstance;
  _serverURL: string;
  _language: string;
  _sdkVersion: string;
  _genVersion: string;

  constructor(
    defaultClient: AxiosInstance,
    securityClient: AxiosInstance,
    serverURL: string,
    language: string,
    sdkVersion: string,
    genVersion: string
  ) {
    this._defaultClient = defaultClient;
    this._securityClient = securityClient;
    this._serverURL = serverURL;
    this._language = language;
    this._sdkVersion = sdkVersion;
    this._genVersion = genVersion;
  }

  /**
   * Add an allowlist of IDP groups for accessing a channel
   *
   * @see {@link https://api.slack.com/methods/admin.conversations.restrictAccess.addGroup} - API method documentation
   */
  async adminConversationsRestrictAccessAddGroup(
    req: operations.AdminConversationsRestrictAccessAddGroupRequestBody,
    security: operations.AdminConversationsRestrictAccessAddGroupSecurity,
    config?: AxiosRequestConfig
  ): Promise<operations.AdminConversationsRestrictAccessAddGroupResponse> {
    if (!(req instanceof utils.SpeakeasyBase)) {
      req = new operations.AdminConversationsRestrictAccessAddGroupRequestBody(
        req
      );
    }

    const baseURL: string = this._serverURL;
    const url: string =
      baseURL.replace(/\/$/, "") +
      "/admin.conversations.restrictAccess.addGroup";

    let [reqBodyHeaders, reqBody]: [object, any] = [{}, {}];

    try {
      [reqBodyHeaders, reqBody] = utils.serializeRequestBody(
        req,
        "request",
        "form"
      );
    } catch (e: unknown) {
      if (e instanceof Error) {
        throw new Error(`Error serializing request body, cause: ${e.message}`);
      }
    }

    if (!(security instanceof utils.SpeakeasyBase)) {
      security =
        new operations.AdminConversationsRestrictAccessAddGroupSecurity(
          security
        );
    }
    const client: AxiosInstance = utils.createSecurityClient(
      this._defaultClient,
      security
    );

    const headers = { ...reqBodyHeaders, ...config?.headers };
    if (reqBody == null || Object.keys(reqBody).length === 0)
      throw new Error("request body is required");

    const httpRes: AxiosResponse = await client.request({
      validateStatus: () => true,
      url: url,
      method: "post",
      headers: headers,
      data: reqBody,
      ...config,
    });

    const contentType: string = httpRes?.headers?.["content-type"] ?? "";

    if (httpRes?.status == null) {
      throw new Error(`status code not found in response: ${httpRes}`);
    }

    const res: operations.AdminConversationsRestrictAccessAddGroupResponse =
      new operations.AdminConversationsRestrictAccessAddGroupResponse({
        statusCode: httpRes.status,
        contentType: contentType,
        rawResponse: httpRes,
      });
    switch (true) {
      case httpRes?.status == 200:
        if (utils.matchContentType(contentType, `application/json`)) {
          res.defaultSuccessTemplate = utils.objectToClass(httpRes?.data);
        }
        break;
      default:
        if (utils.matchContentType(contentType, `application/json`)) {
          res.defaultErrorTemplate = utils.objectToClass(httpRes?.data);
        }
        break;
    }

    return res;
  }

  /**
   * List all IDP Groups linked to a channel
   *
   * @see {@link https://api.slack.com/methods/admin.conversations.restrictAccess.listGroups} - API method documentation
   */
  async adminConversationsRestrictAccessListGroups(
    req: operations.AdminConversationsRestrictAccessListGroupsRequest,
    security: operations.AdminConversationsRestrictAccessListGroupsSecurity,
    config?: AxiosRequestConfig
  ): Promise<operations.AdminConversationsRestrictAccessListGroupsResponse> {
    if (!(req instanceof utils.SpeakeasyBase)) {
      req = new operations.AdminConversationsRestrictAccessListGroupsRequest(
        req
      );
    }

    const baseURL: string = this._serverURL;
    const url: string =
      baseURL.replace(/\/$/, "") +
      "/admin.conversations.restrictAccess.listGroups";

    if (!(security instanceof utils.SpeakeasyBase)) {
      security =
        new operations.AdminConversationsRestrictAccessListGroupsSecurity(
          security
        );
    }
    const client: AxiosInstance = utils.createSecurityClient(
      this._defaultClient,
      security
    );

    const queryParams: string = utils.serializeQueryParams(req);

    const httpRes: AxiosResponse = await client.request({
      validateStatus: () => true,
      url: url + queryParams,
      method: "get",
      ...config,
    });

    const contentType: string = httpRes?.headers?.["content-type"] ?? "";

    if (httpRes?.status == null) {
      throw new Error(`status code not found in response: ${httpRes}`);
    }

    const res: operations.AdminConversationsRestrictAccessListGroupsResponse =
      new operations.AdminConversationsRestrictAccessListGroupsResponse({
        statusCode: httpRes.status,
        contentType: contentType,
        rawResponse: httpRes,
      });
    switch (true) {
      case httpRes?.status == 200:
        if (utils.matchContentType(contentType, `application/json`)) {
          res.defaultSuccessTemplate = utils.objectToClass(httpRes?.data);
        }
        break;
      default:
        if (utils.matchContentType(contentType, `application/json`)) {
          res.defaultErrorTemplate = utils.objectToClass(httpRes?.data);
        }
        break;
    }

    return res;
  }

  /**
   * Remove a linked IDP group linked from a private channel
   *
   * @see {@link https://api.slack.com/methods/admin.conversations.restrictAccess.removeGroup} - API method documentation
   */
  async adminConversationsRestrictAccessRemoveGroup(
    req: operations.AdminConversationsRestrictAccessRemoveGroupRequestBody,
    security: operations.AdminConversationsRestrictAccessRemoveGroupSecurity,
    config?: AxiosRequestConfig
  ): Promise<operations.AdminConversationsRestrictAccessRemoveGroupResponse> {
    if (!(req instanceof utils.SpeakeasyBase)) {
      req =
        new operations.AdminConversationsRestrictAccessRemoveGroupRequestBody(
          req
        );
    }

    const baseURL: string = this._serverURL;
    const url: string =
      baseURL.replace(/\/$/, "") +
      "/admin.conversations.restrictAccess.removeGroup";

    let [reqBodyHeaders, reqBody]: [object, any] = [{}, {}];

    try {
      [reqBodyHeaders, reqBody] = utils.serializeRequestBody(
        req,
        "request",
        "form"
      );
    } catch (e: unknown) {
      if (e instanceof Error) {
        throw new Error(`Error serializing request body, cause: ${e.message}`);
      }
    }

    if (!(security instanceof utils.SpeakeasyBase)) {
      security =
        new operations.AdminConversationsRestrictAccessRemoveGroupSecurity(
          security
        );
    }
    const client: AxiosInstance = utils.createSecurityClient(
      this._defaultClient,
      security
    );

    const headers = { ...reqBodyHeaders, ...config?.headers };
    if (reqBody == null || Object.keys(reqBody).length === 0)
      throw new Error("request body is required");

    const httpRes: AxiosResponse = await client.request({
      validateStatus: () => true,
      url: url,
      method: "post",
      headers: headers,
      data: reqBody,
      ...config,
    });

    const contentType: string = httpRes?.headers?.["content-type"] ?? "";

    if (httpRes?.status == null) {
      throw new Error(`status code not found in response: ${httpRes}`);
    }

    const res: operations.AdminConversationsRestrictAccessRemoveGroupResponse =
      new operations.AdminConversationsRestrictAccessRemoveGroupResponse({
        statusCode: httpRes.status,
        contentType: contentType,
        rawResponse: httpRes,
      });
    switch (true) {
      case httpRes?.status == 200:
        if (utils.matchContentType(contentType, `application/json`)) {
          res.defaultSuccessTemplate = utils.objectToClass(httpRes?.data);
        }
        break;
      default:
        if (utils.matchContentType(contentType, `application/json`)) {
          res.defaultErrorTemplate = utils.objectToClass(httpRes?.data);
        }
        break;
    }

    return res;
  }
}
